pipeline {
    agent {
        label 'AGENT-1'
    }

    environment {
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '850960379432'
        PROJECT = 'robboshop'
    }

    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    
    stages{
        stage('Init'){
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 00-vpc
                        terraform init --reconfigure
                        """
                    }
                }
            }
        }
        stage('plan'){
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 00-vpc
                        terraform plan
                        """
                    }
                }
            }
        }
        stage('aplly'){
            input{
                message "Should we continue?"
                ok "yes we can.."
                submitter Arun
            }
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 00-vpc
                        terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'I will always say hello again'
            deleteDir()
        }

        success {
            echo 'Hello Success'
        }

        failure {
            echo "Hello Failure"
        }

    }
}