pipeline {
    agent {
        label 'AGENT-1'
    }

    environment {
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '850960379432'
        PROJECT = 'robboshop'
    }

    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    
    stages{
        stage('Init'){
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 00-vpc
                        terraform init --reconfigure
                        """
                    }
                }
            }
        }
    }

}