pipeline {
    agent {
        label 'AGENT-1'
    }

    environment {
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '850960379432'
        PROJECT = 'robboshop'
    }

    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    
    stages{
        stage('Init'){
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 10-sg
                        terraform init --reconfigure
                        """
                    }
                }
            }
        }
        stage('plan'){
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 10-sg
                        terraform plan
                        """
                    }
                }
            }
        }
        stage('apply'){
            input{
                message "Should we continue?"
                ok "yes we can.."
                submitter "Arun"
            }
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                        cd 10-sg
                        terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        //Triggering the DownStream Job
        stage('Trigger the bastion EKS ACM ALB'){
            parallel {
                stage(trigger bastion) {
                    steps{
                        script {
                            build job: '20-bastion',
                            propagate: false,
                            wait: false

                        }
                    }
                }
                stage(trigger EKS) {
                    steps{
                        script {
                            build job: '80-eks',
                            propagate: false,
                            wait: false
                        }
                    }
                }
                stage(trigger ACM) {
                    steps{
                        script {
                            build job: '60-acm',
                            propagate: false,
                            wait: false

                        }
                    }
                }
            }
        }
        stage(trigger ALB) {
                    steps{
                        script {
                            build job: '70-ingress-alb',
                            propagate: false,
                            wait: false

                        }
                    }
        }
    }

    post {
        always {
            echo 'I will always say hello again'
            deleteDir()
        }

        success {
            echo 'Hello Success'
        }

        failure {
            echo "Hello Failure"
        }

    }
}